general:
 buildTool: "mta"

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  Acceptance:
    cloudFoundryDeploy: false

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "49ebaa58trial_dev-sys-wo7aphwr"
    cfSpace: "DEV"
    cfCredentialsId: "dcf-dev-subaccount"
    tmsUpload: false
steps:

  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint: {}